### ISSUE TITLE
"Insert" button does not work on first selection

### ISSUE THREAD

**Issue by mor10** [ImageFlow/imageflow-prototype#38] opened 2015-03-09 21:03 UTC
After entering the modal and clicking an image the "Insert" button is highlighted but does not work. To use the "Insert" function the user must click "View" and then "Insert".

I'm assuming this is to prevent the user from inserting an image without adding metadata as we discussed. If that's the case then the button highlighting needs to change for a clearer user flow:

1. User selects image
2. If no metadata exists only the "View" button becomes active and is highlighted
3. If metadata already exists "View" and "Insert" buttons are active and "Insert" button is highlighted

**Comment by aymanalzarrad** [comment] 2015-03-09 22:05
I don't believe that this was done intentionally. If this is the target behavior then we have to change it back as the button will work again once #37 is merged.

**Comment by teamAris** [comment] 2015-03-10 00:49
This was not intended behavior - the metadata conversation is another
can of worms entirely.

**Closed** 2015-03-10 03:04 UTC
Labels: bug, Scenario 1, Scenario 2
